version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
          export GIT_COMMIT_HASH=`git log -n1 --pretty='%h'`
          export BUILD_TIME=`date +"%Y-%m-%d %H:%M:%S"`
          echo '{ "git.commit.hash": "$GIT_COMMIT_HASH", "build.time": "$BUILD_TIME" }' > ./hello-world-app/public/config.json

       # build the application image
      - run: docker build -t xlitil/hello-world-app:$CIRCLE_BRANCH ./hello-world-app

      # deploy the image
      - run: |
          echo Login with $DOCKER_USER
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push xlitil/hello-world-app:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: docker-registry
