version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
          export GIT_COMMIT_HASH=`git log -n1 --pretty='%h'`
          export BUILD_TIME=`date +"%Y-%m-%d %H:%M:%S"`
          echo "{ \"git.commit.hash\": \"$GIT_COMMIT_HASH\", \"build.time\": \"$BUILD_TIME\" }" > ./hello-world-app/public/config.json

       # build the application image
      - run: |
          docker build -t xlitil/hello-world-app:$CIRCLE_BRANCH ./hello-world-app
          export IMAGE_ID=`docker images xlitil/hello-world-app:$CIRCLE_BRANCH --quiet`

      - run: |
          echo Login with $DOCKER_USER
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push xlitil/hello-world-app:$CIRCLE_BRANCH

      # create build config file for next jobs
      - run: |
          mkdir -p buildConfig
          echo "#!/bin/bash" > buildConfig/config.sh
          echo "export GIT_COMMIT_HASH=\"$GIT_COMMIT_HASH\"" >> buildConfig/config.sh
          echo "export BUILD_TIME=\"$BUILD_TIME\"" >> buildConfig/config.sh
          echo "export IMAGE_ID=\"$IMAGE_ID\"" >> buildConfig/config.sh

      - persist_to_workspace:
          root: buildConfig
          paths:
            - config.sh

  tag-release:
    machine: true
    steps:
      - attach_workspace:
          at: buildConfig

      - run: |
          . buildConfig/config.sh
          cat buildConfig/config.sh
          echo $GIT_COMMIT_HASH

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: docker-registry
      - promote:
          type: approval
          requires:
           - build
      - tag-release:
          requires:
            - promote
