apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
      env: DEV
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        env: DEV
    spec:
      containers:
      - name: hello-world
        image: xlitil/hello-world-app:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: JUMBOTRON_COLOR
          #value: "#4186f4"
          value: "#f44242"
