apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-lb
spec:
  rules:
  - host: dev-xlitil.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world-svc-dev
          servicePort: 80
