apiVersion: v1
kind: Service
metadata:
  name: hello-world-srv
  labels:
    run: hello-world-srv-run
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
