apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc-dev
  labels:
    env: DEV
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
    env: DEV
